### ISSUE TITLE
is this compatible with ionic 3??

### ISSUE THREAD

**Issue by castelar007** [mariusbackes/cordova-plugin-theme-detection#1]
getting an error:
Uncaught (in promise): TypeError: Object(__WEBPACK_IMPORTED_MODULE_1__ionic_native_core__["cordova"]) is not a function

**Comment by mariusbackes** [comment]
If you are using the **@ionic-native wrapper** for this plugin, you should update the **@ionic-native/core** to the latest version by installing:
`npm i @ionic-native/core@latest`

After that, you have to update your packages and change the import from:
`import { ThemeDetection } from "@ionic-native/theme-detection";`

to

`import { ThemeDetection } from "@ionic-native/theme-detection/ngx";`

Also update your other installed plugins to the latest versions and at the **ngx** to the import

**Comment by mariusbackes** [comment]
If you are still have the problem take a look at the following repository which uses the plugin with Ionic 3: [Ionic 3 Theme Detection](https://github.com/angelofan/theme-detection-ionic3)

**Comment by svzi** [comment]
@mariusbackes The last with Ionic3 compatible package version of `@ionic-native/core` is `4.17.0`. So updating to the latest version is not a good idea...

Also the sample you provide, doesn't even import the plugin:
https://github.com/angelofan/theme-detection-ionic3/blob/master/src/app/app.module.ts

Btw. the import from `.../ngx` usually points to imports for Ionic4+. I would expect to import the Ionic3 version of the plugin from `@ionic-native/theme-detection`, but that doesn't work.

Any help would be really much appreciated.
